"""
Plot histogram of average ratings (product level) generated by avg_rating.tsv
"""
import pandas as pd, matplotlib.pyplot as plt, pathlib

df = pd.read_csv("output/avg_rating.tsv", sep="\t",
                 names=["parent_asin","avg_rating"], encoding="utf-16")
plt.figure(figsize=(8,4))
df["avg_rating"].plot.hist(bins=40)
plt.title("Distribution of Average Ratings per Product")
plt.xlabel("Average Rating")
plt.tight_layout()
fig_path = pathlib.Path("figs/avg_rating_hist.png")
fig_path.parent.mkdir(parents=True, exist_ok=True)
plt.savefig(fig_path, dpi=300)
print("Saved figure", fig_path)
